"""Engine runtime: timeframe preparation, combo task/row building, regime signals."""

import json
import os

import numpy as np
import pandas as pd


def _prepare_timeframe_runtime(
    *,
    timeframe,
    data_days,
    base_symbol,
    trade_symbols,
    exchange,
    cache_dir,
    cache_format,
    vol_lookbacks,
    mom_lookbacks,
    trade_mom_lookbacks,
    rsi_window,
    bb_window,
    bb_alpha,
    atr_window,
    ma_pairs,
    obv_lookbacks,
    volume_lookbacks,
    roc_lookbacks,
    cmf_lookbacks,
    mfi_window,
    vroc_lookbacks,
    ad_lookbacks,
    cci_lookbacks,
    willr_lookbacks,
    adx_lookbacks,
    trix_lookbacks,
    dpo_lookbacks,
    efi_lookbacks,
    vwma_lookbacks,
    ultosc_periods,
    keltner_lookbacks,
    donchian_lookbacks,
    ppo_fast,
    ppo_slow,
    ppo_signal,
    chop_lookbacks,
    init_cash_usdt,
    capital_mode,
    wf_train_days,
    wf_test_days,
    wf_step_days,
    wf_mode,
    wf_valid_days=0,
    fees,
    slippage_bps,
    spread_bps,
    funding_rate_daily,
    order_size_pct,
    max_concurrent_positions,
    config_sha256,
    bar_hours,
    prepare_timeframe_context_fn,
    build_walk_forward_windows_fn,
    compute_data_fingerprint_fn,
):
    ctx = prepare_timeframe_context_fn(
        timeframe=timeframe,
        data_days=data_days,
        base_symbol=base_symbol,
        trade_symbols=trade_symbols,
        exchange=exchange,
        cache_dir=cache_dir,
        cache_format=cache_format,
        vol_lookbacks=vol_lookbacks,
        mom_lookbacks=mom_lookbacks,
        trade_mom_lookbacks=trade_mom_lookbacks,
        rsi_window=rsi_window,
        bb_window=bb_window,
        bb_alpha=bb_alpha,
        atr_window=atr_window,
        ma_pairs=ma_pairs,
        obv_lookbacks=obv_lookbacks,
        volume_lookbacks=volume_lookbacks,
        roc_lookbacks=roc_lookbacks,
        cmf_lookbacks=cmf_lookbacks,
        mfi_window=mfi_window,
        vroc_lookbacks=vroc_lookbacks,
        ad_lookbacks=ad_lookbacks,
        cci_lookbacks=cci_lookbacks,
        willr_lookbacks=willr_lookbacks,
        adx_lookbacks=adx_lookbacks,
        trix_lookbacks=trix_lookbacks,
        dpo_lookbacks=dpo_lookbacks,
        efi_lookbacks=efi_lookbacks,
        vwma_lookbacks=vwma_lookbacks,
        ultosc_periods=ultosc_periods,
        keltner_lookbacks=keltner_lookbacks,
        donchian_lookbacks=donchian_lookbacks,
        ppo_fast=ppo_fast,
        ppo_slow=ppo_slow,
        ppo_signal=ppo_signal,
        chop_lookbacks=chop_lookbacks,
        init_cash_usdt=init_cash_usdt,
        capital_mode=capital_mode,
    )
    trade_symbols_tf = ctx["trade_symbols"]
    timeframe_range = f"{timeframe} ({data_days}d): {ctx['data_range']}"
    timeframe_data_fingerprint = compute_data_fingerprint_fn(
        {
            "exchange": exchange,
            "base_symbol": base_symbol,
            "trade_symbols": trade_symbols_tf,
            "timeframe": timeframe,
            "data_days": data_days,
            "data_start": str(ctx["trade_close"].index[0]),
            "data_end": str(ctx["trade_close"].index[-1]),
        }
    )
    wf_windows = build_walk_forward_windows_fn(
        ctx["trade_close"].index,
        wf_train_days,
        wf_test_days,
        wf_step_days,
        mode=wf_mode,
        valid_days=wf_valid_days,
    )
    wf_slices = [(test_start, test_end) for _, _, _, _, test_start, test_end in wf_windows]
    runtime_eval = {
        "ctx": ctx,
        "trade_symbols_tf": trade_symbols_tf,
        "timeframe": timeframe,
        "data_days": data_days,
        "exchange": exchange,
        "base_symbol": base_symbol,
        "capital_mode": capital_mode,
        "fees": fees,
        "slippage_bps": slippage_bps,
        "spread_bps": spread_bps,
        "funding_rate_daily": funding_rate_daily,
        "order_size_pct": order_size_pct,
        "max_concurrent_positions": max_concurrent_positions,
        "init_cash_usdt": init_cash_usdt,
        "wf_train_days": wf_train_days,
        "wf_test_days": wf_test_days,
        "wf_step_days": wf_step_days,
        "wf_valid_days": wf_valid_days,
        "wf_mode": wf_mode,
        "rsi_window": rsi_window,
        "bar_hours": bar_hours,
        "wf_windows": wf_windows,
        "wf_slices": wf_slices,
        "config_sha256": config_sha256,
        "data_fingerprint": timeframe_data_fingerprint,
    }
    return {
        "ctx": ctx,
        "trade_symbols_tf": trade_symbols_tf,
        "timeframe_range": timeframe_range,
        "timeframe_data_fingerprint": timeframe_data_fingerprint,
        "wf_windows": wf_windows,
        "wf_slices": wf_slices,
        "runtime_eval": runtime_eval,
    }


def _build_combo_key_values(
    timeframe,
    data_days,
    exchange,
    base_symbol,
    trade_symbols_tf,
    capital_mode,
    fees,
    slippage_bps,
    spread_bps,
    funding_rate_daily,
    order_size_pct,
    max_concurrent_positions,
    init_cash_usdt,
    wf_train_days,
    wf_test_days,
    wf_step_days,
    data_start,
    data_end,
    regime,
    filter_name,
    indicator_list,
    indicator_combo,
    vol_lookback,
    vol_z,
    mom_lookback,
    trade_mom_lookback,
    tp_stop,
    sl_stop,
    max_hold,
    rsi_window,
    param_payload,
    wf_mode="anchored",
    wf_valid_days=0,
):
    return {
        "timeframe": timeframe,
        "data_days": data_days,
        "exchange": exchange,
        "base_symbol": base_symbol,
        "trade_symbols_key": ",".join(trade_symbols_tf),
        "capital_mode": capital_mode,
        "fees": fees,
        "slippage_bps": slippage_bps,
        "spread_bps": spread_bps,
        "funding_rate_daily": funding_rate_daily,
        "order_size_pct": order_size_pct,
        "max_concurrent_positions": max_concurrent_positions,
        "init_cash_usdt": init_cash_usdt,
        "wf_train_days": wf_train_days,
        "wf_test_days": wf_test_days,
        "wf_step_days": wf_step_days,
        "wf_valid_days": wf_valid_days,
        "wf_mode": wf_mode,
        "data_start": str(data_start),
        "data_end": str(data_end),
        "regime_name": regime["regime_name"],
        "regime_type": regime["regime_type"],
        "vol_mode": regime["vol_mode"],
        "regime_rsi_long": regime.get("rsi_pair", (None, None))[0]
        if regime["regime_type"] == "rsi_revert"
        else None,
        "regime_rsi_short": regime.get("rsi_pair", (None, None))[1]
        if regime["regime_type"] == "rsi_revert"
        else None,
        "filter_name": filter_name,
        "indicator_list": indicator_list,
        "indicator_count": len(indicator_combo),
        "vol_lookback": vol_lookback if regime["vol_mode"] != "any" else None,
        "vol_z": vol_z if regime["vol_mode"] != "any" else None,
        "mom_lookback": mom_lookback if regime["regime_type"] == "trend" else None,
        "trade_mom_lookback": trade_mom_lookback,
        "tp_stop": tp_stop,
        "sl_stop": sl_stop,
        "max_hold": max_hold,
        "rsi_window": rsi_window if "rsi" in indicator_combo else None,
        "rsi_long": param_payload["rsi_long"],
        "rsi_short": param_payload["rsi_short"],
        "bb_width": param_payload["bb_width"],
        "atr_ratio": param_payload["atr_ratio"],
        "ma_fast": param_payload["ma_fast"],
        "ma_slow": param_payload["ma_slow"],
        "macd_hist_ratio": param_payload["macd_hist_ratio"],
        "stoch_long": param_payload["stoch_long"],
        "stoch_short": param_payload["stoch_short"],
        "obv_lookback": param_payload["obv_lookback"],
        "volume_lookback": param_payload["volume_lookback"],
        "volume_z": param_payload["volume_z"],
        "roc_lookback": param_payload["roc_lookback"],
        "roc_threshold": param_payload["roc_threshold"],
        "mfi_long": param_payload["mfi_long"],
        "mfi_short": param_payload["mfi_short"],
        "cmf_lookback": param_payload["cmf_lookback"],
        "cmf_threshold": param_payload["cmf_threshold"],
        "vroc_lookback": param_payload["vroc_lookback"],
        "vroc_threshold": param_payload["vroc_threshold"],
        "ad_lookback": param_payload["ad_lookback"],
    }


def _build_combo_task_payload(
    *,
    timeframe,
    data_days,
    exchange,
    base_symbol,
    trade_symbols_tf,
    capital_mode,
    fees,
    slippage_bps,
    spread_bps,
    funding_rate_daily,
    order_size_pct,
    max_concurrent_positions,
    init_cash_usdt,
    wf_train_days,
    wf_test_days,
    wf_step_days,
    wf_mode,
    wf_valid_days=0,
    data_start,
    data_end,
    regime,
    indicator_combo,
    combo_params,
    vol_lookback,
    vol_z,
    mom_lookback,
    trade_mom_lookback,
    tp_stop,
    sl_stop,
    max_hold,
    rsi_window,
    indicator_param_fields,
    combo_key_from_dict_fn,
    indicator_combo_label_fn,
):
    indicator_combo = tuple(indicator_combo)
    combo_params = dict(combo_params)
    indicator_list = ",".join(indicator_combo)
    filter_name = indicator_combo_label_fn(indicator_combo)
    param_payload = {field: combo_params.get(field) for field in indicator_param_fields}
    combo_key_values = _build_combo_key_values(
        timeframe=timeframe,
        data_days=data_days,
        exchange=exchange,
        base_symbol=base_symbol,
        trade_symbols_tf=trade_symbols_tf,
        capital_mode=capital_mode,
        fees=fees,
        slippage_bps=slippage_bps,
        spread_bps=spread_bps,
        funding_rate_daily=funding_rate_daily,
        order_size_pct=order_size_pct,
        max_concurrent_positions=max_concurrent_positions,
        init_cash_usdt=init_cash_usdt,
        wf_train_days=wf_train_days,
        wf_test_days=wf_test_days,
        wf_step_days=wf_step_days,
        wf_mode=wf_mode,
        wf_valid_days=wf_valid_days,
        data_start=data_start,
        data_end=data_end,
        regime=regime,
        filter_name=filter_name,
        indicator_list=indicator_list,
        indicator_combo=indicator_combo,
        vol_lookback=vol_lookback,
        vol_z=vol_z,
        mom_lookback=mom_lookback,
        trade_mom_lookback=trade_mom_lookback,
        tp_stop=tp_stop,
        sl_stop=sl_stop,
        max_hold=max_hold,
        rsi_window=rsi_window,
        param_payload=param_payload,
    )
    combo_key = combo_key_from_dict_fn(combo_key_values)
    task_payload = {
        "combo_key": combo_key,
        "regime": regime,
        "indicator_combo": indicator_combo,
        "combo_params": combo_params,
        "filter_name": filter_name,
        "indicator_list": indicator_list,
        "vol_lookback": vol_lookback,
        "vol_z": vol_z,
        "mom_lookback": mom_lookback,
        "trade_mom_lookback": trade_mom_lookback,
        "tp_stop": tp_stop,
        "sl_stop": sl_stop,
        "max_hold": max_hold,
    }
    return combo_key, task_payload


def _resolve_regime_signals(regime, vol_cond, ctx, mom_lookback):
    if regime["regime_type"] == "trend":
        mom = ctx["mom_by_lb"][mom_lookback]
        return vol_cond & (mom > 0), vol_cond & (mom < 0), None, None
    if regime["regime_type"] == "rsi_revert":
        regime_rsi_long, regime_rsi_short = regime["rsi_pair"]
        return (
            vol_cond & (ctx["rsi_series"] < regime_rsi_long),
            vol_cond & (ctx["rsi_series"] > regime_rsi_short),
            regime_rsi_long,
            regime_rsi_short,
        )
    if regime["regime_type"] == "bb_revert":
        return (
            vol_cond & (ctx["btc_close"] < ctx["bb_lower"]),
            vol_cond & (ctx["btc_close"] > ctx["bb_upper"]),
            None,
            None,
        )
    return (
        vol_cond & (ctx["btc_close"] > ctx["bb_upper"]),
        vol_cond & (ctx["btc_close"] < ctx["bb_lower"]),
        None,
        None,
    )


def _build_symbol_row(
    timeframe,
    data_days,
    exchange,
    base_symbol,
    trade_symbols_tf,
    capital_mode,
    fees,
    order_size_pct,
    max_concurrent_positions,
    init_cash_usdt,
    wf_train_days,
    wf_test_days,
    wf_step_days,
    data_start,
    data_end,
    symbol,
    regime,
    regime_rsi_long,
    regime_rsi_short,
    filter_name,
    indicator_list,
    indicator_combo,
    vol_lookback,
    vol_z,
    mom_lookback,
    trade_mom_lookback,
    tp_stop,
    sl_stop,
    max_hold,
    rsi_window,
    variant_params,
    metrics,
    wf_mode="anchored",
    wf_valid_days=0,
    config_sha256=None,
    data_fingerprint=None,
):
    return {
        "timeframe": timeframe,
        "data_days": data_days,
        "exchange": exchange,
        "base_symbol": base_symbol,
        "trade_symbols_key": ",".join(trade_symbols_tf),
        "capital_mode": capital_mode,
        "fees": fees,
        "order_size_pct": order_size_pct,
        "max_concurrent_positions": max_concurrent_positions,
        "init_cash_usdt": init_cash_usdt,
        "wf_train_days": wf_train_days,
        "wf_test_days": wf_test_days,
        "wf_step_days": wf_step_days,
        "wf_valid_days": wf_valid_days,
        "wf_mode": wf_mode,
        "data_start": str(data_start),
        "data_end": str(data_end),
        "config_sha256": config_sha256,
        "data_fingerprint": data_fingerprint,
        "symbol": symbol,
        "regime_name": regime["regime_name"],
        "regime_type": regime["regime_type"],
        "vol_mode": regime["vol_mode"],
        "regime_rsi_long": regime_rsi_long,
        "regime_rsi_short": regime_rsi_short,
        "filter_name": filter_name,
        "indicator_list": indicator_list,
        "indicator_count": len(indicator_combo),
        "vol_lookback": vol_lookback if regime["vol_mode"] != "any" else None,
        "vol_z": vol_z if regime["vol_mode"] != "any" else None,
        "mom_lookback": mom_lookback if regime["regime_type"] == "trend" else None,
        "trade_mom_lookback": trade_mom_lookback,
        "tp_stop": tp_stop,
        "sl_stop": sl_stop,
        "max_hold": max_hold,
        "rsi_window": rsi_window if "rsi" in indicator_combo else None,
        "rsi_long": variant_params["rsi_long"],
        "rsi_short": variant_params["rsi_short"],
        "bb_width": variant_params["bb_width"],
        "atr_ratio": variant_params["atr_ratio"],
        "ma_fast": variant_params["ma_fast"],
        "ma_slow": variant_params["ma_slow"],
        "macd_hist_ratio": variant_params["macd_hist_ratio"],
        "stoch_long": variant_params["stoch_long"],
        "stoch_short": variant_params["stoch_short"],
        "obv_lookback": variant_params["obv_lookback"],
        "volume_lookback": variant_params["volume_lookback"],
        "volume_z": variant_params["volume_z"],
        "roc_lookback": variant_params["roc_lookback"],
        "roc_threshold": variant_params["roc_threshold"],
        "mfi_long": variant_params["mfi_long"],
        "mfi_short": variant_params["mfi_short"],
        "cmf_lookback": variant_params["cmf_lookback"],
        "cmf_threshold": variant_params["cmf_threshold"],
        "vroc_lookback": variant_params["vroc_lookback"],
        "vroc_threshold": variant_params["vroc_threshold"],
        "ad_lookback": variant_params["ad_lookback"],
        "total_return_pct": float(metrics["total_return_pct"][symbol]),
        "total_profit": float(metrics["total_profit"][symbol]),
        "total_trades": float(metrics["total_trades"][symbol]),
        "win_rate_pct": float(metrics["win_rate_pct"][symbol]),
        "avg_trade_pct": float(metrics["avg_trade_pct"][symbol]),
        "max_drawdown_pct": float(metrics["max_drawdown_pct"][symbol]),
        "position_coverage_pct": float(metrics["position_coverage_pct"][symbol]),
        "avg_hold_hours": float(metrics["avg_hold_hours"][symbol]),
    }


def _build_combo_row(
    timeframe,
    data_days,
    exchange,
    base_symbol,
    trade_symbols_tf,
    capital_mode,
    fees,
    slippage_bps,
    spread_bps,
    funding_rate_daily,
    order_size_pct,
    max_concurrent_positions,
    init_cash_usdt,
    wf_train_days,
    wf_test_days,
    wf_step_days,
    data_start,
    data_end,
    regime,
    regime_rsi_long,
    regime_rsi_short,
    filter_name,
    indicator_list,
    indicator_combo,
    vol_lookback,
    vol_z,
    mom_lookback,
    trade_mom_lookback,
    tp_stop,
    sl_stop,
    max_hold,
    rsi_window,
    variant_params,
    combo_metrics,
    sym_metrics,
    metrics,
    ctx_total_days,
    oos_metrics,
    wf_mode="anchored",
    wf_valid_days=0,
    config_sha256=None,
    data_fingerprint=None,
):
    combo_row = {
        "timeframe": timeframe,
        "data_days": data_days,
        "exchange": exchange,
        "base_symbol": base_symbol,
        "trade_symbols_key": ",".join(trade_symbols_tf),
        "capital_mode": capital_mode,
        "fees": fees,
        "slippage_bps": slippage_bps,
        "spread_bps": spread_bps,
        "funding_rate_daily": funding_rate_daily,
        "order_size_pct": order_size_pct,
        "max_concurrent_positions": max_concurrent_positions,
        "init_cash_usdt": init_cash_usdt,
        "wf_train_days": wf_train_days,
        "wf_test_days": wf_test_days,
        "wf_step_days": wf_step_days,
        "wf_valid_days": wf_valid_days,
        "wf_mode": wf_mode,
        "data_start": str(data_start),
        "data_end": str(data_end),
        "config_sha256": config_sha256,
        "data_fingerprint": data_fingerprint,
        "regime_name": regime["regime_name"],
        "regime_type": regime["regime_type"],
        "vol_mode": regime["vol_mode"],
        "regime_rsi_long": regime_rsi_long,
        "regime_rsi_short": regime_rsi_short,
        "filter_name": filter_name,
        "indicator_list": indicator_list,
        "indicator_count": len(indicator_combo),
        "vol_lookback": vol_lookback if regime["vol_mode"] != "any" else None,
        "vol_z": vol_z if regime["vol_mode"] != "any" else None,
        "mom_lookback": mom_lookback if regime["regime_type"] == "trend" else None,
        "trade_mom_lookback": trade_mom_lookback,
        "tp_stop": tp_stop,
        "sl_stop": sl_stop,
        "max_hold": max_hold,
        "rsi_window": rsi_window if "rsi" in indicator_combo else None,
        "rsi_long": variant_params["rsi_long"],
        "rsi_short": variant_params["rsi_short"],
        "bb_width": variant_params["bb_width"],
        "atr_ratio": variant_params["atr_ratio"],
        "ma_fast": variant_params["ma_fast"],
        "ma_slow": variant_params["ma_slow"],
        "macd_hist_ratio": variant_params["macd_hist_ratio"],
        "stoch_long": variant_params["stoch_long"],
        "stoch_short": variant_params["stoch_short"],
        "obv_lookback": variant_params["obv_lookback"],
        "volume_lookback": variant_params["volume_lookback"],
        "volume_z": variant_params["volume_z"],
        "roc_lookback": variant_params["roc_lookback"],
        "roc_threshold": variant_params["roc_threshold"],
        "mfi_long": variant_params["mfi_long"],
        "mfi_short": variant_params["mfi_short"],
        "cmf_lookback": variant_params["cmf_lookback"],
        "cmf_threshold": variant_params["cmf_threshold"],
        "vroc_lookback": variant_params["vroc_lookback"],
        "vroc_threshold": variant_params["vroc_threshold"],
        "ad_lookback": variant_params["ad_lookback"],
        "avg_total_return_pct": combo_metrics["total_return_pct"],
        "avg_win_rate_pct": combo_metrics["win_rate_pct"],
        "avg_avg_trade_pct": combo_metrics["avg_trade_pct"],
        "avg_max_drawdown_pct": combo_metrics["max_drawdown_pct"],
        "avg_position_coverage_pct": combo_metrics["position_coverage_pct"],
        "avg_total_trades": combo_metrics["total_trades"],
        "min_total_trades": combo_metrics["total_trades"],
        "avg_daily_trades": float(combo_metrics["total_trades"]) / max(ctx_total_days, 1),
        "avg_hold_hours": combo_metrics["avg_hold_hours"],
        "sym_avg_total_return_pct": sym_metrics["avg_total_return_pct"],
        "sym_avg_win_rate_pct": sym_metrics["avg_win_rate_pct"],
        "sym_avg_avg_trade_pct": sym_metrics["avg_avg_trade_pct"],
        "sym_avg_max_drawdown_pct": sym_metrics["avg_max_drawdown_pct"],
        "sym_avg_position_coverage_pct": sym_metrics["avg_position_coverage_pct"],
        "sym_avg_total_trades": sym_metrics["avg_total_trades"],
        "sym_min_total_trades": sym_metrics["min_total_trades"],
        "sym_avg_daily_trades": float(metrics["total_trades"].sum()) / max(ctx_total_days, 1),
        "sym_avg_hold_hours": sym_metrics["avg_hold_hours"],
    }
    combo_row.update(oos_metrics)
    return combo_row


def _append_eval_result_rows(
    *,
    result,
    task_meta,
    timeframe,
    data_days,
    exchange,
    base_symbol,
    trade_symbols_tf,
    capital_mode,
    fees,
    slippage_bps,
    spread_bps,
    funding_rate_daily,
    order_size_pct,
    max_concurrent_positions,
    init_cash_usdt,
    wf_train_days,
    wf_test_days,
    wf_step_days,
    wf_mode,
    wf_valid_days=0,
    data_start,
    data_end,
    rsi_window,
    config_sha256,
    timeframe_data_fingerprint,
    ctx_total_days,
    pending_symbol_rows,
    pending_combo_rows,
    build_symbol_row_fn,
    build_combo_row_fn,
):
    metrics_values = result.get("metrics_values")
    if not isinstance(metrics_values, dict):
        return False

    regime = task_meta["regime"]
    indicator_combo = tuple(task_meta["indicator_combo"])
    filter_name = task_meta["filter_name"]
    indicator_list = task_meta["indicator_list"]
    vol_lookback = task_meta["vol_lookback"]
    vol_z = task_meta["vol_z"]
    mom_lookback = task_meta["mom_lookback"]
    trade_mom_lookback = task_meta["trade_mom_lookback"]
    tp_stop = task_meta["tp_stop"]
    sl_stop = task_meta["sl_stop"]
    max_hold = task_meta["max_hold"]
    metrics = {name: pd.Series(values).reindex(trade_symbols_tf) for name, values in metrics_values.items()}
    variant_params = result["variant_params"]
    regime_rsi_long = result["regime_rsi_long"]
    regime_rsi_short = result["regime_rsi_short"]

    for symbol in trade_symbols_tf:
        pending_symbol_rows.append(
            build_symbol_row_fn(
                timeframe=timeframe,
                data_days=data_days,
                exchange=exchange,
                base_symbol=base_symbol,
                trade_symbols_tf=trade_symbols_tf,
                capital_mode=capital_mode,
                fees=fees,
                order_size_pct=order_size_pct,
                max_concurrent_positions=max_concurrent_positions,
                init_cash_usdt=init_cash_usdt,
                wf_train_days=wf_train_days,
                wf_test_days=wf_test_days,
                wf_step_days=wf_step_days,
                wf_mode=wf_mode,
                data_start=data_start,
                data_end=data_end,
                symbol=symbol,
                regime=regime,
                regime_rsi_long=regime_rsi_long,
                regime_rsi_short=regime_rsi_short,
                filter_name=filter_name,
                indicator_list=indicator_list,
                indicator_combo=indicator_combo,
                vol_lookback=vol_lookback,
                vol_z=vol_z,
                mom_lookback=mom_lookback,
                trade_mom_lookback=trade_mom_lookback,
                tp_stop=tp_stop,
                sl_stop=sl_stop,
                max_hold=max_hold,
                rsi_window=rsi_window,
                variant_params=variant_params,
                metrics=metrics,
                config_sha256=config_sha256,
                data_fingerprint=timeframe_data_fingerprint,
            )
        )

    combo_row = build_combo_row_fn(
        timeframe=timeframe,
        data_days=data_days,
        exchange=exchange,
        base_symbol=base_symbol,
        trade_symbols_tf=trade_symbols_tf,
        capital_mode=capital_mode,
        fees=fees,
        slippage_bps=slippage_bps,
        spread_bps=spread_bps,
        funding_rate_daily=funding_rate_daily,
        order_size_pct=order_size_pct,
        max_concurrent_positions=max_concurrent_positions,
        init_cash_usdt=init_cash_usdt,
        wf_train_days=wf_train_days,
        wf_test_days=wf_test_days,
        wf_step_days=wf_step_days,
        wf_mode=wf_mode,
        data_start=data_start,
        data_end=data_end,
        regime=regime,
        regime_rsi_long=regime_rsi_long,
        regime_rsi_short=regime_rsi_short,
        filter_name=filter_name,
        indicator_list=indicator_list,
        indicator_combo=indicator_combo,
        vol_lookback=vol_lookback,
        vol_z=vol_z,
        mom_lookback=mom_lookback,
        trade_mom_lookback=trade_mom_lookback,
        tp_stop=tp_stop,
        sl_stop=sl_stop,
        max_hold=max_hold,
        rsi_window=rsi_window,
        variant_params=variant_params,
        combo_metrics=result["combo_metrics"],
        sym_metrics=result["sym_metrics"],
        metrics=metrics,
        ctx_total_days=ctx_total_days,
        oos_metrics=result["oos_metrics"],
        config_sha256=config_sha256,
        data_fingerprint=timeframe_data_fingerprint,
    )
    pending_combo_rows.append(combo_row)
    return True


def _compute_effective_costs(fees, slippage_bps, spread_bps, funding_rate_daily, max_hold, bar_hours):
    effective_slippage = (slippage_bps + (spread_bps / 2.0)) / 10000.0
    funding_fee = funding_rate_daily * (max_hold * bar_hours / 24.0)
    effective_fees = fees + funding_fee
    return effective_fees, effective_slippage


def _build_trade_mom_filters(trade_mom):
    return trade_mom > 0, trade_mom < 0



