"""Engine finalize: result loading, finalize pipeline, metadata persistence."""

import json
import os

import numpy as np
import pandas as pd

from .benchmark import compute_bh_return_pct, compute_random_entry_return_pct
from .engine_helpers import _fallback_activity_filter
from .ranking import _dedup_by_combo_group
from .engine_report import (
    _append_leaderboard_row,
    _build_best_report_frames,
    _build_leaderboard_report_html,
    _build_leaderboard_views,
    _build_report_file_paths,
    _build_report_html,
    _build_report_table_html_sections,
    _prepare_best_replay_payload,
    _write_report_files,
)


def _build_finalize_pipeline_kwargs(
    *,
    combo_path,
    per_symbol_path,
    out_dir,
    run_id,
    timeframe_configs,
    timeframe_days_map,
    safe_int_fn,
    min_avg_daily_trades_target,
    apply_quality_filters_fn,
    top_by_score_impl_fn,
    ranking_config,
    history_rows,
    base_symbol,
    trade_symbols,
    exchange,
    cache_dir,
    cache_format,
    vol_lookbacks,
    vol_zs,
    mom_lookbacks,
    trade_mom_lookbacks,
    rsi_window,
    bb_window,
    bb_alpha,
    atr_window,
    ma_pairs,
    obv_lookbacks,
    volume_lookbacks,
    roc_lookbacks,
    cmf_lookbacks,
    mfi_window,
    vroc_lookbacks,
    ad_lookbacks,
    cci_lookbacks,
    willr_lookbacks,
    adx_lookbacks,
    trix_lookbacks,
    dpo_lookbacks,
    efi_lookbacks,
    vwma_lookbacks,
    ultosc_periods,
    keltner_lookbacks,
    donchian_lookbacks,
    ppo_fast,
    ppo_slow,
    ppo_signal,
    chop_lookbacks,
    init_cash_usdt,
    capital_mode,
    wf_train_days,
    wf_test_days,
    wf_step_days,
    wf_valid_days=0,
    wf_mode,
    indicator_param_fields,
    fees,
    slippage_bps,
    spread_bps,
    funding_rate_daily,
    order_size_pct,
    max_concurrent_positions,
    labels,
    config_sha256,
    timestamp_utc,
    leaderboard_path,
    run_metadata_path,
    run_metadata_path_run,
    registry_path,
    search_mode,
    config_path,
    prepare_timeframe_context_fn,
    indicator_combo_label_fn,
    coerce_indicator_params_fn,
    pick_series_from_map_fn,
    apply_indicator_combo_fn,
    timeframe_to_hours_fn,
    run_pf_fn,
    plot_portfolio_fn,
    calc_pf_series_fn,
    build_walk_forward_slices_fn,
    df_to_html_fn,
    combine_data_fingerprints_fn,
    write_run_metadata_fn,
    update_run_registry_fn,
    htf_trend_timeframes=None,
    htf_trend_windows=None,
    combo_seed=None,
    workspace_paths=None,
):
    top_by_score_fn = lambda df, top_n, tie_break_avg_hold: top_by_score_impl_fn(
        df,
        top_n=top_n,
        tie_break_avg_hold=tie_break_avg_hold,
        ranking_config=ranking_config,
    )
    return {
        "combo_path": combo_path,
        "per_symbol_path": per_symbol_path,
        "out_dir": out_dir,
        "run_id": run_id,
        "timeframe_configs": timeframe_configs,
        "timeframe_days_map": timeframe_days_map,
        "safe_int_fn": safe_int_fn,
        "min_avg_daily_trades_target": min_avg_daily_trades_target,
        "apply_quality_filters_fn": apply_quality_filters_fn,
        "top_by_score_fn": top_by_score_fn,
        "history_rows": history_rows,
        "top_by_score_leaderboard_fn": top_by_score_fn,
        "base_symbol": base_symbol,
        "trade_symbols": trade_symbols,
        "exchange": exchange,
        "cache_dir": cache_dir,
        "cache_format": cache_format,
        "vol_lookbacks": vol_lookbacks,
        "vol_zs": vol_zs,
        "mom_lookbacks": mom_lookbacks,
        "trade_mom_lookbacks": trade_mom_lookbacks,
        "rsi_window": rsi_window,
        "bb_window": bb_window,
        "bb_alpha": bb_alpha,
        "atr_window": atr_window,
        "ma_pairs": ma_pairs,
        "obv_lookbacks": obv_lookbacks,
        "volume_lookbacks": volume_lookbacks,
        "roc_lookbacks": roc_lookbacks,
        "cmf_lookbacks": cmf_lookbacks,
        "mfi_window": mfi_window,
        "vroc_lookbacks": vroc_lookbacks,
        "ad_lookbacks": ad_lookbacks,
        "cci_lookbacks": cci_lookbacks,
        "willr_lookbacks": willr_lookbacks,
        "adx_lookbacks": adx_lookbacks,
        "trix_lookbacks": trix_lookbacks,
        "dpo_lookbacks": dpo_lookbacks,
        "efi_lookbacks": efi_lookbacks,
        "vwma_lookbacks": vwma_lookbacks,
        "ultosc_periods": ultosc_periods,
        "keltner_lookbacks": keltner_lookbacks,
        "donchian_lookbacks": donchian_lookbacks,
        "ppo_fast": ppo_fast,
        "ppo_slow": ppo_slow,
        "ppo_signal": ppo_signal,
        "chop_lookbacks": chop_lookbacks,
        "init_cash_usdt": init_cash_usdt,
        "capital_mode": capital_mode,
        "htf_trend_timeframes": htf_trend_timeframes,
        "htf_trend_windows": htf_trend_windows,
        "wf_train_days": wf_train_days,
        "wf_test_days": wf_test_days,
        "wf_step_days": wf_step_days,
        "wf_valid_days": wf_valid_days,
        "wf_mode": wf_mode,
        "indicator_param_fields": indicator_param_fields,
        "fees": fees,
        "slippage_bps": slippage_bps,
        "spread_bps": spread_bps,
        "funding_rate_daily": funding_rate_daily,
        "order_size_pct": order_size_pct,
        "max_concurrent_positions": max_concurrent_positions,
        "labels": labels,
        "config_sha256": config_sha256,
        "combo_seed": combo_seed,
        "timestamp_utc": timestamp_utc,
        "ranking_config": ranking_config,
        "leaderboard_path": leaderboard_path,
        "run_metadata_path": run_metadata_path,
        "run_metadata_path_run": run_metadata_path_run,
        "registry_path": registry_path,
        "workspace_paths": workspace_paths,
        "search_mode": search_mode,
        "config_path": config_path,
        "prepare_timeframe_context_fn": prepare_timeframe_context_fn,
        "indicator_combo_label_fn": indicator_combo_label_fn,
        "coerce_indicator_params_fn": coerce_indicator_params_fn,
        "pick_series_from_map_fn": pick_series_from_map_fn,
        "apply_indicator_combo_fn": apply_indicator_combo_fn,
        "timeframe_to_hours_fn": timeframe_to_hours_fn,
        "run_pf_fn": run_pf_fn,
        "plot_portfolio_fn": plot_portfolio_fn,
        "calc_pf_series_fn": calc_pf_series_fn,
        "build_walk_forward_slices_fn": build_walk_forward_slices_fn,
        "df_to_html_fn": df_to_html_fn,
        "combine_data_fingerprints_fn": combine_data_fingerprints_fn,
        "write_run_metadata_fn": write_run_metadata_fn,
        "update_run_registry_fn": update_run_registry_fn,
    }


def _build_finalize_pipeline_context(
    *,
    combo_path,
    per_symbol_path,
    out_dir,
    run_id,
    timeframe_configs,
    timeframe_days_map,
    safe_int_fn,
    min_avg_daily_trades_target,
    apply_quality_filters_fn,
    top_by_score_impl_fn,
    ranking_config,
    history_rows,
    base_symbol,
    trade_symbols,
    exchange,
    cache_dir,
    cache_format,
    vol_lookbacks,
    vol_zs,
    mom_lookbacks,
    trade_mom_lookbacks,
    rsi_window,
    bb_window,
    bb_alpha,
    atr_window,
    ma_pairs,
    obv_lookbacks,
    volume_lookbacks,
    roc_lookbacks,
    cmf_lookbacks,
    mfi_window,
    vroc_lookbacks,
    ad_lookbacks,
    cci_lookbacks,
    willr_lookbacks,
    adx_lookbacks,
    trix_lookbacks,
    dpo_lookbacks,
    efi_lookbacks,
    vwma_lookbacks,
    ultosc_periods,
    keltner_lookbacks,
    donchian_lookbacks,
    ppo_fast,
    ppo_slow,
    ppo_signal,
    chop_lookbacks,
    init_cash_usdt,
    capital_mode,
    wf_train_days,
    wf_test_days,
    wf_step_days,
    wf_valid_days=0,
    wf_mode,
    indicator_param_fields,
    fees,
    slippage_bps,
    spread_bps,
    funding_rate_daily,
    order_size_pct,
    max_concurrent_positions,
    labels,
    config_sha256,
    timestamp_utc,
    leaderboard_path,
    run_metadata_path,
    run_metadata_path_run,
    registry_path,
    search_mode,
    config_path,
    prepare_timeframe_context_fn,
    indicator_combo_label_fn,
    coerce_indicator_params_fn,
    pick_series_from_map_fn,
    apply_indicator_combo_fn,
    timeframe_to_hours_fn,
    run_pf_fn,
    plot_portfolio_fn,
    calc_pf_series_fn,
    build_walk_forward_slices_fn,
    df_to_html_fn,
    combine_data_fingerprints_fn,
    write_run_metadata_fn,
    update_run_registry_fn,
    htf_trend_timeframes=None,
    htf_trend_windows=None,
    combo_seed=None,
    workspace_paths=None,
):
    return {
        "combo_path": combo_path,
        "per_symbol_path": per_symbol_path,
        "out_dir": out_dir,
        "run_id": run_id,
        "timeframe_configs": timeframe_configs,
        "timeframe_days_map": timeframe_days_map,
        "safe_int_fn": safe_int_fn,
        "min_avg_daily_trades_target": min_avg_daily_trades_target,
        "apply_quality_filters_fn": apply_quality_filters_fn,
        "top_by_score_impl_fn": top_by_score_impl_fn,
        "ranking_config": ranking_config,
        "history_rows": history_rows,
        "base_symbol": base_symbol,
        "trade_symbols": trade_symbols,
        "exchange": exchange,
        "cache_dir": cache_dir,
        "cache_format": cache_format,
        "vol_lookbacks": vol_lookbacks,
        "vol_zs": vol_zs,
        "mom_lookbacks": mom_lookbacks,
        "trade_mom_lookbacks": trade_mom_lookbacks,
        "rsi_window": rsi_window,
        "bb_window": bb_window,
        "bb_alpha": bb_alpha,
        "atr_window": atr_window,
        "ma_pairs": ma_pairs,
        "obv_lookbacks": obv_lookbacks,
        "volume_lookbacks": volume_lookbacks,
        "roc_lookbacks": roc_lookbacks,
        "cmf_lookbacks": cmf_lookbacks,
        "mfi_window": mfi_window,
        "vroc_lookbacks": vroc_lookbacks,
        "ad_lookbacks": ad_lookbacks,
        "cci_lookbacks": cci_lookbacks,
        "willr_lookbacks": willr_lookbacks,
        "adx_lookbacks": adx_lookbacks,
        "trix_lookbacks": trix_lookbacks,
        "dpo_lookbacks": dpo_lookbacks,
        "efi_lookbacks": efi_lookbacks,
        "vwma_lookbacks": vwma_lookbacks,
        "ultosc_periods": ultosc_periods,
        "keltner_lookbacks": keltner_lookbacks,
        "donchian_lookbacks": donchian_lookbacks,
        "ppo_fast": ppo_fast,
        "ppo_slow": ppo_slow,
        "ppo_signal": ppo_signal,
        "chop_lookbacks": chop_lookbacks,
        "init_cash_usdt": init_cash_usdt,
        "capital_mode": capital_mode,
        "htf_trend_timeframes": htf_trend_timeframes,
        "htf_trend_windows": htf_trend_windows,
        "wf_train_days": wf_train_days,
        "wf_test_days": wf_test_days,
        "wf_step_days": wf_step_days,
        "wf_valid_days": wf_valid_days,
        "wf_mode": wf_mode,
        "indicator_param_fields": indicator_param_fields,
        "fees": fees,
        "slippage_bps": slippage_bps,
        "spread_bps": spread_bps,
        "funding_rate_daily": funding_rate_daily,
        "order_size_pct": order_size_pct,
        "max_concurrent_positions": max_concurrent_positions,
        "labels": labels,
        "config_sha256": config_sha256,
        "combo_seed": combo_seed,
        "timestamp_utc": timestamp_utc,
        "leaderboard_path": leaderboard_path,
        "run_metadata_path": run_metadata_path,
        "run_metadata_path_run": run_metadata_path_run,
        "registry_path": registry_path,
        "workspace_paths": workspace_paths,
        "search_mode": search_mode,
        "config_path": config_path,
        "prepare_timeframe_context_fn": prepare_timeframe_context_fn,
        "indicator_combo_label_fn": indicator_combo_label_fn,
        "coerce_indicator_params_fn": coerce_indicator_params_fn,
        "pick_series_from_map_fn": pick_series_from_map_fn,
        "apply_indicator_combo_fn": apply_indicator_combo_fn,
        "timeframe_to_hours_fn": timeframe_to_hours_fn,
        "run_pf_fn": run_pf_fn,
        "plot_portfolio_fn": plot_portfolio_fn,
        "calc_pf_series_fn": calc_pf_series_fn,
        "build_walk_forward_slices_fn": build_walk_forward_slices_fn,
        "df_to_html_fn": df_to_html_fn,
        "combine_data_fingerprints_fn": combine_data_fingerprints_fn,
        "write_run_metadata_fn": write_run_metadata_fn,
        "update_run_registry_fn": update_run_registry_fn,
    }


def _build_finalize_pipeline_context_from_shared(
    *,
    shared_pipeline_runtime_context,
    combo_path,
    per_symbol_path,
    out_dir,
    run_id,
    timeframe_configs,
    timeframe_days_map,
    safe_int_fn,
    min_avg_daily_trades_target,
    apply_quality_filters_fn,
    top_by_score_impl_fn,
    ranking_config,
    history_rows,
    labels,
    timestamp_utc,
    leaderboard_path,
    run_metadata_path,
    run_metadata_path_run,
    registry_path,
    search_mode,
    config_path,
    prepare_timeframe_context_fn,
    indicator_combo_label_fn,
    coerce_indicator_params_fn,
    pick_series_from_map_fn,
    apply_indicator_combo_fn,
    timeframe_to_hours_fn,
    run_pf_fn,
    plot_portfolio_fn,
    calc_pf_series_fn,
    build_walk_forward_slices_fn,
    df_to_html_fn,
    combine_data_fingerprints_fn,
    write_run_metadata_fn,
    update_run_registry_fn,
    workspace_paths=None,
):
    shared = dict(shared_pipeline_runtime_context)
    return _build_finalize_pipeline_context(
        combo_path=combo_path,
        per_symbol_path=per_symbol_path,
        out_dir=out_dir,
        run_id=run_id,
        timeframe_configs=timeframe_configs,
        timeframe_days_map=timeframe_days_map,
        safe_int_fn=safe_int_fn,
        min_avg_daily_trades_target=min_avg_daily_trades_target,
        apply_quality_filters_fn=apply_quality_filters_fn,
        top_by_score_impl_fn=top_by_score_impl_fn,
        ranking_config=ranking_config,
        history_rows=history_rows,
        base_symbol=shared["base_symbol"],
        trade_symbols=shared["trade_symbols"],
        exchange=shared["exchange"],
        cache_dir=shared["cache_dir"],
        cache_format=shared["cache_format"],
        vol_lookbacks=shared["vol_lookbacks"],
        vol_zs=shared["vol_zs"],
        mom_lookbacks=shared["mom_lookbacks"],
        trade_mom_lookbacks=shared["trade_mom_lookbacks"],
        rsi_window=shared["rsi_window"],
        bb_window=shared["bb_window"],
        bb_alpha=shared["bb_alpha"],
        atr_window=shared["atr_window"],
        ma_pairs=shared["ma_pairs"],
        obv_lookbacks=shared["obv_lookbacks"],
        volume_lookbacks=shared["volume_lookbacks"],
        roc_lookbacks=shared["roc_lookbacks"],
        cmf_lookbacks=shared["cmf_lookbacks"],
        mfi_window=shared["mfi_window"],
        vroc_lookbacks=shared["vroc_lookbacks"],
        ad_lookbacks=shared["ad_lookbacks"],
        cci_lookbacks=shared["cci_lookbacks"],
        willr_lookbacks=shared["willr_lookbacks"],
        adx_lookbacks=shared["adx_lookbacks"],
        trix_lookbacks=shared["trix_lookbacks"],
        dpo_lookbacks=shared["dpo_lookbacks"],
        efi_lookbacks=shared["efi_lookbacks"],
        vwma_lookbacks=shared["vwma_lookbacks"],
        ultosc_periods=shared["ultosc_periods"],
        keltner_lookbacks=shared["keltner_lookbacks"],
        donchian_lookbacks=shared["donchian_lookbacks"],
        ppo_fast=shared["ppo_fast"],
        ppo_slow=shared["ppo_slow"],
        ppo_signal=shared["ppo_signal"],
        chop_lookbacks=shared["chop_lookbacks"],
        init_cash_usdt=shared["init_cash_usdt"],
        capital_mode=shared["capital_mode"],
        htf_trend_timeframes=shared["htf_trend_timeframes"],
        htf_trend_windows=shared["htf_trend_windows"],
        wf_train_days=shared["wf_train_days"],
        wf_test_days=shared["wf_test_days"],
        wf_step_days=shared["wf_step_days"],
        wf_valid_days=shared["wf_valid_days"],
        wf_mode=shared["wf_mode"],
        indicator_param_fields=shared["indicator_param_fields"],
        fees=shared["fees"],
        slippage_bps=shared["slippage_bps"],
        spread_bps=shared["spread_bps"],
        funding_rate_daily=shared["funding_rate_daily"],
        order_size_pct=shared["order_size_pct"],
        max_concurrent_positions=shared["max_concurrent_positions"],
        labels=labels,
        config_sha256=shared["config_sha256"],
        combo_seed=shared.get("combo_seed"),
        timestamp_utc=timestamp_utc,
        leaderboard_path=leaderboard_path,
        run_metadata_path=run_metadata_path,
        run_metadata_path_run=run_metadata_path_run,
        registry_path=registry_path,
        workspace_paths=workspace_paths,
        search_mode=search_mode,
        config_path=config_path,
        prepare_timeframe_context_fn=prepare_timeframe_context_fn,
        indicator_combo_label_fn=indicator_combo_label_fn,
        coerce_indicator_params_fn=coerce_indicator_params_fn,
        pick_series_from_map_fn=pick_series_from_map_fn,
        apply_indicator_combo_fn=apply_indicator_combo_fn,
        timeframe_to_hours_fn=timeframe_to_hours_fn,
        run_pf_fn=run_pf_fn,
        plot_portfolio_fn=plot_portfolio_fn,
        calc_pf_series_fn=calc_pf_series_fn,
        build_walk_forward_slices_fn=build_walk_forward_slices_fn,
        df_to_html_fn=df_to_html_fn,
        combine_data_fingerprints_fn=combine_data_fingerprints_fn,
        write_run_metadata_fn=write_run_metadata_fn,
        update_run_registry_fn=update_run_registry_fn,
    )


def _build_finalize_pipeline_kwargs_from_context(
    *,
    finalize_pipeline_context,
):
    context = dict(finalize_pipeline_context)
    return _build_finalize_pipeline_kwargs(**context)


def _load_result_frames(combo_path, per_symbol_path):
    combo_df = pd.read_csv(combo_path, low_memory=False) if os.path.exists(combo_path) else pd.DataFrame()
    per_symbol_df = (
        pd.read_csv(per_symbol_path, low_memory=False) if os.path.exists(per_symbol_path) else pd.DataFrame()
    )
    return combo_df, per_symbol_df


def _write_run_snapshot_files(combo_df, per_symbol_df, out_dir, run_id):
    combo_path_run = os.path.join(out_dir, f"param_sweep_combo_summary_{run_id}.csv")
    per_symbol_path_run = os.path.join(out_dir, f"param_sweep_symbol_summary_{run_id}.csv")
    if not combo_df.empty:
        combo_df.to_csv(combo_path_run, index=False)
    if not per_symbol_df.empty:
        per_symbol_df.to_csv(per_symbol_path_run, index=False)
    return combo_path_run, per_symbol_path_run


def _derive_workspace_report_paths(workspace_paths, report_file_run, run_id):
    if not workspace_paths:
        return None
    report_paths = workspace_paths.get("report_paths")
    if report_paths:
        return report_paths
    reports_dir = workspace_paths.get("reports_dir")
    if not reports_dir:
        return None
    report_name = os.path.basename(report_file_run)
    latest_name = report_name.replace(f"_{run_id}", "")
    return {
        "report_run": os.path.join(reports_dir, report_name),
        "report_latest": os.path.join(reports_dir, latest_name),
    }


def _select_current_combo_df(combo_df, timeframe_configs):
    combo_df_current = combo_df
    if "timeframe" in combo_df.columns:
        valid_timeframes = {cfg["timeframe"] for cfg in timeframe_configs}
        tf_subset = combo_df[combo_df["timeframe"].isin(valid_timeframes)].copy()
        if not tf_subset.empty:
            combo_df_current = tf_subset
    return combo_df_current


def _pick_best_from_top(top_df, timeframe_configs, timeframe_days_map, safe_int_fn):
    best = top_df.iloc[0].to_dict()
    best_timeframe = best.get("timeframe")
    if best_timeframe is None or (isinstance(best_timeframe, float) and np.isnan(best_timeframe)):
        best_timeframe = timeframe_configs[0]["timeframe"]
    best_timeframe = str(best_timeframe)
    if best_timeframe not in timeframe_days_map:
        best_timeframe = timeframe_configs[0]["timeframe"]
    best_data_days = safe_int_fn(
        best.get("data_days"),
        timeframe_days_map.get(best_timeframe, timeframe_configs[0]["days"]),
    )
    return best, best_timeframe, best_data_days


def _build_leaderboard_row_payload(
    *,
    run_id,
    timestamp_utc,
    config_sha256,
    ranking_mode,
    plot_symbol,
    best_timeframe,
    best_data_days,
    min_avg_daily_trades_target,
    min_avg_daily_trades_filter,
    capital_mode,
    init_cash_usdt,
    order_size_pct,
    max_concurrent_positions,
    slippage_bps,
    spread_bps,
    funding_rate_daily,
    wf_train_days,
    wf_test_days,
    wf_step_days,
    wf_valid_days=0,
    wf_mode,
    wf_segments,
    best,
    report_file,
    bh_return_pct=None,
    random_entry_return_pct=None,
):
    return {
        "run_id": run_id,
        "timestamp_utc": timestamp_utc,
        "config_sha256": config_sha256,
        "data_fingerprint": best.get("data_fingerprint"),
        "ranking_mode": ranking_mode,
        "plot_symbol": plot_symbol,
        "timeframe": best_timeframe,
        "data_days": best_data_days,
        "min_avg_daily_trades_target": min_avg_daily_trades_target,
        "min_avg_daily_trades_filter": min_avg_daily_trades_filter,
        "capital_mode": capital_mode,
        "init_cash_usdt": init_cash_usdt,
        "order_size_pct": order_size_pct,
        "max_concurrent_positions": max_concurrent_positions,
        "slippage_bps": slippage_bps,
        "spread_bps": spread_bps,
        "funding_rate_daily": funding_rate_daily,
        "wf_train_days": wf_train_days,
        "wf_test_days": wf_test_days,
        "wf_step_days": wf_step_days,
        "wf_valid_days": wf_valid_days,
        "wf_mode": wf_mode,
        "wf_segments": wf_segments,
        "regime_name": best.get("regime_name"),
        "regime_type": best.get("regime_type"),
        "vol_mode": best.get("vol_mode"),
        "regime_rsi_long": best.get("regime_rsi_long"),
        "regime_rsi_short": best.get("regime_rsi_short"),
        "filter_name": best.get("filter_name"),
        "indicator_list": best.get("indicator_list"),
        "indicator_count": best.get("indicator_count"),
        "vol_lookback": best.get("vol_lookback"),
        "vol_z": best.get("vol_z"),
        "mom_lookback": best.get("mom_lookback"),
        "trade_mom_lookback": best.get("trade_mom_lookback"),
        "tp_stop": best.get("tp_stop"),
        "sl_stop": best.get("sl_stop"),
        "max_hold": best.get("max_hold"),
        "rsi_window": best.get("rsi_window"),
        "rsi_long": best.get("rsi_long"),
        "rsi_short": best.get("rsi_short"),
        "bb_width": best.get("bb_width"),
        "atr_ratio": best.get("atr_ratio"),
        "ma_fast": best.get("ma_fast"),
        "ma_slow": best.get("ma_slow"),
        "macd_hist_ratio": best.get("macd_hist_ratio"),
        "stoch_long": best.get("stoch_long"),
        "stoch_short": best.get("stoch_short"),
        "obv_lookback": best.get("obv_lookback"),
        "volume_lookback": best.get("volume_lookback"),
        "volume_z": best.get("volume_z"),
        "roc_lookback": best.get("roc_lookback"),
        "roc_threshold": best.get("roc_threshold"),
        "mfi_long": best.get("mfi_long"),
        "mfi_short": best.get("mfi_short"),
        "cmf_lookback": best.get("cmf_lookback"),
        "cmf_threshold": best.get("cmf_threshold"),
        "vroc_lookback": best.get("vroc_lookback"),
        "vroc_threshold": best.get("vroc_threshold"),
        "ad_lookback": best.get("ad_lookback"),
        "avg_total_return_pct": best.get("avg_total_return_pct"),
        "avg_daily_trades": best.get("avg_daily_trades"),
        "avg_hold_hours": best.get("avg_hold_hours"),
        "avg_position_coverage_pct": best.get("avg_position_coverage_pct"),
        "avg_total_trades": best.get("avg_total_trades"),
        "min_total_trades": best.get("min_total_trades"),
        "oos_avg_total_return_pct": best.get("oos_avg_total_return_pct"),
        "oos_avg_win_rate_pct": best.get("oos_avg_win_rate_pct"),
        "oos_avg_avg_trade_pct": best.get("oos_avg_avg_trade_pct"),
        "oos_avg_max_drawdown_pct": best.get("oos_avg_max_drawdown_pct"),
        "oos_avg_position_coverage_pct": best.get("oos_avg_position_coverage_pct"),
        "oos_avg_total_trades": best.get("oos_avg_total_trades"),
        "oos_min_total_trades": best.get("oos_min_total_trades"),
        "oos_avg_daily_trades": best.get("oos_avg_daily_trades"),
        "oos_avg_hold_hours": best.get("oos_avg_hold_hours"),
        "oos_return_std": best.get("oos_return_std"),
        "oos_positive_segment_ratio": best.get("oos_positive_segment_ratio"),
        "oos_sharpe_like": best.get("oos_sharpe_like"),
        "oos_low_trade_segment_ratio": best.get("oos_low_trade_segment_ratio"),
        "oos_low_trade_penalty": best.get("oos_low_trade_penalty"),
        "oos_segments": best.get("oos_segments"),
        "bh_return_pct": bh_return_pct,
        "random_entry_return_pct": random_entry_return_pct,
        "report_file": report_file,
    }


def _build_run_metadata_payload(
    *,
    run_id,
    timestamp_utc,
    search_mode,
    config_sha256,
    data_fingerprint,
    config_path,
    exchange,
    base_symbol,
    trade_symbols,
    timeframe_configs,
    wf_train_days,
    wf_test_days,
    wf_step_days,
    wf_valid_days=0,
    wf_mode,
    capital_mode,
    init_cash_usdt,
    ranking_config,
    timeframe_diagnostics=None,
    combo_seed=None,
):
    return {
        "run_id": run_id,
        "timestamp_utc": timestamp_utc,
        "search_mode": search_mode,
        "config_sha256": config_sha256,
        "combo_seed": combo_seed,
        "data_fingerprint": data_fingerprint,
        "config_path": config_path,
        "exchange": exchange,
        "base_symbol": base_symbol,
        "trade_symbols": trade_symbols,
        "timeframes": timeframe_configs,
        "timeframe_diagnostics": list(timeframe_diagnostics or []),
        "wf_train_days": wf_train_days,
        "wf_test_days": wf_test_days,
        "wf_step_days": wf_step_days,
        "wf_valid_days": wf_valid_days,
        "wf_mode": wf_mode,
        "capital_mode": capital_mode,
        "init_cash_usdt": init_cash_usdt,
        "ranking": ranking_config,
    }


def _prepare_best_timeframe_context(
    *,
    best_timeframe,
    best_data_days,
    base_symbol,
    trade_symbols,
    exchange,
    cache_dir,
    cache_format,
    vol_lookbacks,
    mom_lookbacks,
    trade_mom_lookbacks,
    rsi_window,
    bb_window,
    bb_alpha,
    atr_window,
    ma_pairs,
    obv_lookbacks,
    volume_lookbacks,
    roc_lookbacks,
    cmf_lookbacks,
    mfi_window,
    vroc_lookbacks,
    ad_lookbacks,
    cci_lookbacks,
    willr_lookbacks,
    adx_lookbacks,
    trix_lookbacks,
    dpo_lookbacks,
    efi_lookbacks,
    vwma_lookbacks,
    ultosc_periods,
    keltner_lookbacks,
    donchian_lookbacks,
    ppo_fast,
    ppo_slow,
    ppo_signal,
    chop_lookbacks,
    init_cash_usdt,
    capital_mode,
    prepare_timeframe_context_fn,
    htf_trend_timeframes=None,
    htf_trend_windows=None,
):
    try:
        ctx = prepare_timeframe_context_fn(
            timeframe=best_timeframe,
            data_days=best_data_days,
            base_symbol=base_symbol,
            trade_symbols=trade_symbols,
            exchange=exchange,
            cache_dir=cache_dir,
            cache_format=cache_format,
            vol_lookbacks=vol_lookbacks,
            mom_lookbacks=mom_lookbacks,
            trade_mom_lookbacks=trade_mom_lookbacks,
            rsi_window=rsi_window,
            bb_window=bb_window,
            bb_alpha=bb_alpha,
            atr_window=atr_window,
            ma_pairs=ma_pairs,
            obv_lookbacks=obv_lookbacks,
            volume_lookbacks=volume_lookbacks,
            roc_lookbacks=roc_lookbacks,
            cmf_lookbacks=cmf_lookbacks,
            mfi_window=mfi_window,
            vroc_lookbacks=vroc_lookbacks,
            ad_lookbacks=ad_lookbacks,
            cci_lookbacks=cci_lookbacks,
            willr_lookbacks=willr_lookbacks,
            adx_lookbacks=adx_lookbacks,
            trix_lookbacks=trix_lookbacks,
            dpo_lookbacks=dpo_lookbacks,
            efi_lookbacks=efi_lookbacks,
            vwma_lookbacks=vwma_lookbacks,
            ultosc_periods=ultosc_periods,
            keltner_lookbacks=keltner_lookbacks,
            donchian_lookbacks=donchian_lookbacks,
            ppo_fast=ppo_fast,
            ppo_slow=ppo_slow,
            ppo_signal=ppo_signal,
            chop_lookbacks=chop_lookbacks,
            init_cash_usdt=init_cash_usdt,
            capital_mode=capital_mode,
            htf_trend_timeframes=htf_trend_timeframes,
            htf_trend_windows=htf_trend_windows,
        )
        return {"ctx": ctx, "error": None}
    except Exception as exc:
        return {"ctx": None, "error": exc}


def _persist_run_metadata_and_registry(
    *,
    timeframe_fingerprints,
    timeframe_diagnostics=None,
    run_id,
    timestamp_utc,
    search_mode,
    config_sha256,
    config_path,
    exchange,
    base_symbol,
    trade_symbols,
    timeframe_configs,
    wf_train_days,
    wf_test_days,
    wf_step_days,
    wf_valid_days=0,
    wf_mode,
    capital_mode,
    init_cash_usdt,
    ranking_config,
    run_metadata_path,
    run_metadata_path_run,
    registry_path,
    leaderboard_row,
    per_symbol_df,
    combine_data_fingerprints_fn,
    write_run_metadata_fn,
    update_run_registry_fn,
    combo_seed=None,
):
    run_data_fingerprint = combine_data_fingerprints_fn(timeframe_fingerprints)
    run_metadata_payload = _build_run_metadata_payload(
        run_id=run_id,
        timestamp_utc=timestamp_utc,
        search_mode=search_mode,
        config_sha256=config_sha256,
        combo_seed=combo_seed,
        data_fingerprint=run_data_fingerprint,
        config_path=config_path,
        exchange=exchange,
        base_symbol=base_symbol,
        trade_symbols=trade_symbols,
        timeframe_configs=timeframe_configs,
        timeframe_diagnostics=timeframe_diagnostics,
        wf_train_days=wf_train_days,
        wf_test_days=wf_test_days,
        wf_step_days=wf_step_days,
        wf_valid_days=wf_valid_days,
        wf_mode=wf_mode,
        capital_mode=capital_mode,
        init_cash_usdt=init_cash_usdt,
        ranking_config=ranking_config,
    )
    write_run_metadata_fn(run_metadata_path, run_metadata_payload)
    write_run_metadata_fn(run_metadata_path_run, run_metadata_payload)
    update_run_registry_fn(
        registry_path=registry_path,
        run_metadata=run_metadata_payload,
        best_row=leaderboard_row,
        per_symbol_df=per_symbol_df,
        updated_utc=timestamp_utc,
    )
    return {"run_data_fingerprint": run_data_fingerprint, "run_metadata_payload": run_metadata_payload}


def _build_completion_output_map(
    *,
    combo_path,
    per_symbol_path,
    top10_path,
    leaderboard_path,
    registry_path,
    run_metadata_path,
    run_metadata_path_run,
    report_path_latest,
    report_path_run,
):
    return {
        "combo_summary": combo_path,
        "per_symbol_summary": per_symbol_path,
        "top10": top10_path,
        "leaderboard": leaderboard_path,
        "run_registry": registry_path,
        "run_metadata": run_metadata_path,
        "run_metadata_run": run_metadata_path_run,
        "report_latest": report_path_latest,
        "report_run": report_path_run,
    }


def _run_finalize_pipeline(
    *,
    combo_path,
    per_symbol_path,
    out_dir,
    run_id,
    timeframe_configs,
    timeframe_days_map,
    safe_int_fn,
    min_avg_daily_trades_target,
    apply_quality_filters_fn,
    top_by_score_fn,
    history_rows,
    top_by_score_leaderboard_fn,
    base_symbol,
    trade_symbols,
    exchange,
    cache_dir,
    cache_format,
    vol_lookbacks,
    vol_zs,
    mom_lookbacks,
    trade_mom_lookbacks,
    rsi_window,
    bb_window,
    bb_alpha,
    atr_window,
    ma_pairs,
    obv_lookbacks,
    volume_lookbacks,
    roc_lookbacks,
    cmf_lookbacks,
    mfi_window,
    vroc_lookbacks,
    ad_lookbacks,
    cci_lookbacks,
    willr_lookbacks,
    adx_lookbacks,
    trix_lookbacks,
    dpo_lookbacks,
    efi_lookbacks,
    vwma_lookbacks,
    ultosc_periods,
    keltner_lookbacks,
    donchian_lookbacks,
    ppo_fast,
    ppo_slow,
    ppo_signal,
    chop_lookbacks,
    init_cash_usdt,
    capital_mode,
    timeframe_ranges,
    wf_train_days,
    wf_test_days,
    wf_step_days,
    wf_valid_days=0,
    wf_mode,
    indicator_param_fields,
    fees,
    slippage_bps,
    spread_bps,
    funding_rate_daily,
    order_size_pct,
    max_concurrent_positions,
    labels,
    config_sha256,
    timestamp_utc,
    ranking_config,
    leaderboard_path,
    run_metadata_path,
    run_metadata_path_run,
    registry_path,
    timeframe_fingerprints,
    timeframe_diagnostics=None,
    search_mode,
    config_path,
    per_symbol_df_for_registry=None,
    prepare_timeframe_context_fn=None,
    indicator_combo_label_fn=None,
    coerce_indicator_params_fn=None,
    pick_series_from_map_fn=None,
    apply_indicator_combo_fn=None,
    timeframe_to_hours_fn=None,
    run_pf_fn=None,
    plot_portfolio_fn=None,
    calc_pf_series_fn=None,
    build_walk_forward_slices_fn=None,
    df_to_html_fn=None,
    combine_data_fingerprints_fn=None,
    write_run_metadata_fn=None,
    update_run_registry_fn=None,
    htf_trend_timeframes=None,
    htf_trend_windows=None,
    combo_seed=None,
    workspace_paths=None,
):
    combo_df, per_symbol_df = _load_result_frames(combo_path, per_symbol_path)
    _write_run_snapshot_files(combo_df, per_symbol_df, out_dir, run_id)

    combo_df_current = _select_current_combo_df(combo_df, timeframe_configs)
    if combo_df_current.empty:
        return {
            "ok": False,
            "warning": "[warn] No valid combinations evaluated; check data download and filters.",
        }

    filtered, min_avg_daily_trades_filter = _fallback_activity_filter(
        combo_df_current=combo_df_current,
        min_avg_daily_trades_target=min_avg_daily_trades_target,
        apply_quality_filters_fn=apply_quality_filters_fn,
    )

    top10_sorted, _ = top_by_score_fn(filtered, top_n=len(filtered), tie_break_avg_hold=True)
    top10 = _dedup_by_combo_group(top10_sorted, ranking_config=ranking_config).head(10)
    top10_path = (workspace_paths.get("top10_path") if workspace_paths else None) or os.path.join(
        out_dir,
        f"param_sweep_top10_{run_id}.csv",
    )
    os.makedirs(os.path.dirname(top10_path), exist_ok=True)
    top10.to_csv(top10_path, index=False)

    best, best_timeframe, best_data_days = _pick_best_from_top(
        top_df=top10,
        timeframe_configs=timeframe_configs,
        timeframe_days_map=timeframe_days_map,
        safe_int_fn=safe_int_fn,
    )

    best_ctx_result = _prepare_best_timeframe_context(
        best_timeframe=best_timeframe,
        best_data_days=best_data_days,
        base_symbol=base_symbol,
        trade_symbols=trade_symbols,
        exchange=exchange,
        cache_dir=cache_dir,
        cache_format=cache_format,
        vol_lookbacks=vol_lookbacks,
        mom_lookbacks=mom_lookbacks,
        trade_mom_lookbacks=trade_mom_lookbacks,
        rsi_window=rsi_window,
        bb_window=bb_window,
        bb_alpha=bb_alpha,
        atr_window=atr_window,
        ma_pairs=ma_pairs,
        obv_lookbacks=obv_lookbacks,
        volume_lookbacks=volume_lookbacks,
        roc_lookbacks=roc_lookbacks,
        cmf_lookbacks=cmf_lookbacks,
        mfi_window=mfi_window,
        vroc_lookbacks=vroc_lookbacks,
        ad_lookbacks=ad_lookbacks,
        cci_lookbacks=cci_lookbacks,
        willr_lookbacks=willr_lookbacks,
        adx_lookbacks=adx_lookbacks,
        trix_lookbacks=trix_lookbacks,
        dpo_lookbacks=dpo_lookbacks,
        efi_lookbacks=efi_lookbacks,
        vwma_lookbacks=vwma_lookbacks,
        ultosc_periods=ultosc_periods,
        keltner_lookbacks=keltner_lookbacks,
        donchian_lookbacks=donchian_lookbacks,
        ppo_fast=ppo_fast,
        ppo_slow=ppo_slow,
        ppo_signal=ppo_signal,
        chop_lookbacks=chop_lookbacks,
        init_cash_usdt=init_cash_usdt,
        capital_mode=capital_mode,
        htf_trend_timeframes=htf_trend_timeframes,
        htf_trend_windows=htf_trend_windows,
        prepare_timeframe_context_fn=prepare_timeframe_context_fn,
    )
    best_ctx = best_ctx_result["ctx"]
    if best_ctx is None:
        return {"ok": False, "warning": f"[warn] best report skipped: {best_ctx_result['error']}"}

    # --- Baseline benchmarks (AWF-020) ---
    _trade_close = best_ctx.get("trade_close")
    if _trade_close is not None and not _trade_close.empty:
        _bh_return_pct = compute_bh_return_pct(_trade_close)
        _random_entry_return_pct = compute_random_entry_return_pct(_trade_close)
    else:
        _bh_return_pct = None
        _random_entry_return_pct = None

    best_replay = _prepare_best_replay_payload(
        best=best,
        best_timeframe=best_timeframe,
        best_ctx=best_ctx,
        timeframe_ranges=timeframe_ranges,
        wf_train_days=wf_train_days,
        wf_test_days=wf_test_days,
        wf_step_days=wf_step_days,
        wf_valid_days=wf_valid_days,
        wf_mode=wf_mode,
        indicator_param_fields=indicator_param_fields,
        vol_lookbacks=vol_lookbacks,
        vol_zs=vol_zs,
        mom_lookbacks=mom_lookbacks,
        trade_mom_lookbacks=trade_mom_lookbacks,
        fees=fees,
        slippage_bps=slippage_bps,
        spread_bps=spread_bps,
        funding_rate_daily=funding_rate_daily,
        order_size_pct=order_size_pct,
        capital_mode=capital_mode,
        max_concurrent_positions=max_concurrent_positions,
        indicator_combo_label_fn=indicator_combo_label_fn,
        coerce_indicator_params_fn=coerce_indicator_params_fn,
        pick_series_from_map_fn=pick_series_from_map_fn,
        apply_indicator_combo_fn=apply_indicator_combo_fn,
        timeframe_to_hours_fn=timeframe_to_hours_fn,
        run_pf_fn=run_pf_fn,
        plot_portfolio_fn=plot_portfolio_fn,
        calc_pf_series_fn=calc_pf_series_fn,
        build_walk_forward_slices_fn=build_walk_forward_slices_fn,
    )

    trade_symbols_report = best_replay["trade_symbols"]
    plot_symbol = best_replay["plot_symbol"]
    data_range = best_replay["data_range"]
    scan_timeframes = best_replay["scan_timeframes"]
    wf_slices = best_replay["wf_slices"]
    best_regime = best_replay["best_regime"]
    indicator_list = best_replay["indicator_list"]
    best_indicator_combo = best_replay["best_indicator_combo"]
    best_filter_name = best_replay["best_filter_name"]
    best_params = best_replay["best_params"]
    best_trade_mom_lookback = best_replay["best_trade_mom_lookback"]
    best_tp_stop = best_replay["best_tp_stop"]
    best_sl_stop = best_replay["best_sl_stop"]
    best_max_hold = best_replay["best_max_hold"]
    best_summary = best_replay["best_summary"]
    plot_html = best_replay["plot_html"]

    report_params, oos_summary = _build_best_report_frames(
        best=best,
        best_timeframe=best_timeframe,
        best_data_days=best_data_days,
        capital_mode=capital_mode,
        wf_mode=wf_mode,
        best_regime=best_regime,
        best_filter_name=best_filter_name,
        indicator_list=indicator_list,
        best_indicator_combo=best_indicator_combo,
        best_trade_mom_lookback=best_trade_mom_lookback,
        best_tp_stop=best_tp_stop,
        best_sl_stop=best_sl_stop,
        best_max_hold=best_max_hold,
        rsi_window=rsi_window,
        best_params=best_params,
    )

    report_tables = _build_report_table_html_sections(
        report_params=report_params,
        oos_summary=oos_summary,
        top10=top10,
        best_summary=best_summary,
        label_map=labels,
        df_to_html_fn=df_to_html_fn,
    )
    report_params_html = report_tables["report_params_html"]
    oos_summary_html = report_tables["oos_summary_html"]
    top10_html = report_tables["top10_html"]
    summary_html = report_tables["summary_html"]

    report_paths = _build_report_file_paths(out_dir=out_dir, plot_symbol=plot_symbol, run_id=run_id)
    report_file_run = report_paths["report_file_run"]
    report_path_latest = report_paths["report_path_latest"]
    report_path_run = report_paths["report_path_run"]
    workspace_report_paths = _derive_workspace_report_paths(workspace_paths, report_file_run, run_id)

    leaderboard_row = _build_leaderboard_row_payload(
        run_id=run_id,
        timestamp_utc=timestamp_utc,
        config_sha256=config_sha256,
        ranking_mode=ranking_config.get("mode"),
        plot_symbol=plot_symbol,
        best_timeframe=best_timeframe,
        best_data_days=best_data_days,
        min_avg_daily_trades_target=min_avg_daily_trades_target,
        min_avg_daily_trades_filter=min_avg_daily_trades_filter,
        capital_mode=capital_mode,
        init_cash_usdt=init_cash_usdt,
        order_size_pct=order_size_pct,
        max_concurrent_positions=max_concurrent_positions,
        slippage_bps=slippage_bps,
        spread_bps=spread_bps,
        funding_rate_daily=funding_rate_daily,
        wf_train_days=wf_train_days,
        wf_test_days=wf_test_days,
        wf_step_days=wf_step_days,
        wf_valid_days=wf_valid_days,
        wf_mode=wf_mode,
        wf_segments=len(wf_slices),
        best=best,
        report_file=report_file_run,
        bh_return_pct=_bh_return_pct,
        random_entry_return_pct=_random_entry_return_pct,
    )

    lb_df = _append_leaderboard_row(leaderboard_path=leaderboard_path, leaderboard_row=leaderboard_row)
    _, lb_recent, lb_best = _build_leaderboard_views(
        lb_df=lb_df,
        history_rows=history_rows,
        top_by_score_fn=top_by_score_leaderboard_fn,
    )
    lb_report = _build_leaderboard_report_html(
        lb_recent=lb_recent,
        lb_best=lb_best,
        label_map=labels,
        df_to_html_fn=df_to_html_fn,
    )
    lb_recent_html = lb_report["lb_recent_html"]
    lb_best_html = lb_report["lb_best_html"]

    html = _build_report_html(
        labels=labels,
        data_range=data_range,
        best_timeframe=best_timeframe,
        best_data_days=best_data_days,
        scan_timeframes=scan_timeframes,
        run_id=run_id,
        timestamp_utc=timestamp_utc,
        min_avg_daily_trades_target=min_avg_daily_trades_target,
        min_avg_daily_trades_filter=min_avg_daily_trades_filter,
        capital_mode=capital_mode,
        init_cash_usdt=init_cash_usdt,
        order_size_pct=order_size_pct,
        max_concurrent_positions=max_concurrent_positions,
        wf_train_days=wf_train_days,
        wf_test_days=wf_test_days,
        wf_step_days=wf_step_days,
        wf_valid_days=wf_valid_days,
        wf_mode=wf_mode,
        wf_segments=len(wf_slices),
        base_symbol=base_symbol,
        trade_symbols=trade_symbols_report,
        summary_html=summary_html,
        report_params_html=report_params_html,
        oos_summary_html=oos_summary_html,
        top10_html=top10_html,
        lb_best_html=lb_best_html,
        lb_recent_html=lb_recent_html,
        plot_symbol=plot_symbol,
        plot_html=plot_html,
    )
    if workspace_report_paths:
        _write_report_files(
            report_path_latest=workspace_report_paths["report_latest"],
            report_path_run=workspace_report_paths["report_run"],
            html=html,
        )
    else:
        _write_report_files(report_path_latest=report_path_latest, report_path_run=report_path_run, html=html)

    _persist_result = _persist_run_metadata_and_registry(
        timeframe_fingerprints=timeframe_fingerprints,
        timeframe_diagnostics=timeframe_diagnostics,
        run_id=run_id,
        timestamp_utc=timestamp_utc,
        search_mode=search_mode,
        config_sha256=config_sha256,
        combo_seed=combo_seed,
        config_path=config_path,
        exchange=exchange,
        base_symbol=base_symbol,
        trade_symbols=trade_symbols_report,
        timeframe_configs=timeframe_configs,
        wf_train_days=wf_train_days,
        wf_test_days=wf_test_days,
        wf_step_days=wf_step_days,
        wf_valid_days=wf_valid_days,
        wf_mode=wf_mode,
        capital_mode=capital_mode,
        init_cash_usdt=init_cash_usdt,
        ranking_config=ranking_config,
        run_metadata_path=run_metadata_path,
        run_metadata_path_run=run_metadata_path_run,
        registry_path=registry_path,
        leaderboard_row=leaderboard_row,
        per_symbol_df=per_symbol_df if per_symbol_df_for_registry is None else per_symbol_df_for_registry,
        combine_data_fingerprints_fn=combine_data_fingerprints_fn,
        write_run_metadata_fn=write_run_metadata_fn,
        update_run_registry_fn=update_run_registry_fn,
    )

    # --- AWF-028: experiment notebook export ---
    notebook_path = None
    try:
        from autowfo.notebook import build_experiment_notebook

        notebook_path = build_experiment_notebook(
            run_id=run_id,
            out_dir=out_dir,
            metadata=_persist_result.get("run_metadata_payload", {}),
            top10_df=top10,
            combo_df=combo_df,
            symbol_df=per_symbol_df,
            leaderboard_row=leaderboard_row,
        )
    except Exception as exc:  # noqa: BLE001
        # Notebook generation is non-critical; log and continue
        print(f"[notebook] WARNING: failed to generate experiment notebook: {exc}")

    completion_outputs = _build_completion_output_map(
        combo_path=combo_path,
        per_symbol_path=per_symbol_path,
        top10_path=top10_path,
        leaderboard_path=leaderboard_path,
        registry_path=registry_path,
        run_metadata_path=run_metadata_path,
        run_metadata_path_run=run_metadata_path_run,
        report_path_latest=(workspace_report_paths["report_latest"] if workspace_report_paths else None) or report_path_latest,
        report_path_run=(workspace_report_paths["report_run"] if workspace_report_paths else None) or report_path_run,
    )
    if notebook_path is not None:
        completion_outputs["experiment_notebook"] = str(notebook_path)
    return {"ok": True, "completion_outputs": completion_outputs}



