"""AWF-028  Experiment notebook export.

Auto-generate a reproducible Jupyter notebook (``.ipynb``) for each run,
containing run metadata, configuration, top-N results, and analysis code
that can be re-executed independently.

Public API
----------
build_experiment_notebook(run_id, out_dir, *, metadata, top10_df, combo_df,
                          symbol_df, leaderboard_row)
    ??pathlib.Path to the written ``.ipynb`` file.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any, Dict, List, Optional

import nbformat
from nbformat.v4 import new_code_cell, new_markdown_cell, new_notebook


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------


def _format_metadata_value(value: Any) -> str:
    if isinstance(value, list):
        return ", ".join(_format_metadata_value(item) for item in value)
    if isinstance(value, dict):
        if "timeframe" in value and "days" in value:
            return f"{value['timeframe']} ({value['days']}d)"
        return json.dumps(value, ensure_ascii=False, sort_keys=True)
    if value is None:
        return ""
    return str(value)


def _md_metadata_section(metadata: Dict[str, Any]) -> str:
    """Build the top-level Markdown cell with run identification."""
    run_id = metadata.get("run_id", "unknown")
    ts = metadata.get("timestamp_utc", "")
    mode = metadata.get("search_mode", "")
    cfg_sha = metadata.get("config_sha256", "")[:12]
    data_fp = metadata.get("data_fingerprint", "")[:12]
    symbols = metadata.get("trade_symbols", [])
    timeframes = metadata.get("timeframes", [])
    wf_mode = metadata.get("wf_mode", "anchored")
    lines = [
        f"# Experiment Notebook `{run_id}`",
        "",
        "| Field | Value |",
        "|---|---|",
        f"| run_id | `{run_id}` |",
        f"| timestamp_utc | `{ts}` |",
        f"| search_mode | `{mode}` |",
        f"| config_sha256 | `{cfg_sha}` |",
        f"| data_fingerprint | `{data_fp}` |",
        f"| symbols | `{_format_metadata_value(symbols)}` |",
        f"| timeframes | `{_format_metadata_value(timeframes)}` |",
        f"| wf_mode | `{wf_mode}` |",
        "",
        "> This notebook was auto-generated by **AUTOWFO** and can be re-executed",
        "> to reproduce the analysis.  Edit freely to explore further.",
    ]
    return "\n".join(lines)


def _code_imports() -> str:
    """Python imports cell."""
    return "\n".join([
        "import json",
        "from pathlib import Path",
        "",
        "import pandas as pd",
        "",
        "# Resolve artifact directory relative to this notebook",
        "NOTEBOOK_DIR = Path('.').resolve()",
        "ARTIFACTS_DIR = NOTEBOOK_DIR  # adjust if notebook is moved",
    ])


def _code_load_metadata(run_id: str) -> str:
    """Cell that loads and displays run_metadata JSON."""
    return "\n".join([
        f'# Load run metadata',
        f'meta_path = ARTIFACTS_DIR / "run_metadata_{run_id}.json"',
        f'if not meta_path.exists():',
        f'    meta_path = ARTIFACTS_DIR / "run_metadata.json"',
        f'with open(meta_path, encoding="utf-8") as f:',
        f'    run_meta = json.load(f)',
        f'print(json.dumps(run_meta, indent=2, ensure_ascii=False))',
    ])


def _code_load_csv(label: str, filename: str, head: int = 20) -> str:
    """Cell that loads a CSV into a DataFrame and displays head."""
    var = label.replace(" ", "_").replace("-", "_").lower()
    lines = [
        f'# {label}',
        f'_{var}_path = ARTIFACTS_DIR / "{filename}"',
        f'if _{var}_path.exists():',
        f'    {var} = pd.read_csv(_{var}_path)',
        f'    display({var}.head({head}))',
        f'    print(f"rows: {{{var}.shape[0]}}, cols: {{{var}.shape[1]}}")',
        f'else:',
        f'    print(f"File not found: {{_{var}_path}}")',
        f'    {var} = pd.DataFrame()',
    ]
    return "\n".join(lines)


def _code_basic_analysis() -> str:
    """Cell with basic OOS analysis on the top-10 DataFrame."""
    return "\n".join([
        "# --- Basic OOS Analysis ---",
        "if not top_10.empty and 'oos_avg_total_return_pct' in top_10.columns:",
        "    print('=== Top-10 OOS Return Distribution ===')",
        "    print(top_10['oos_avg_total_return_pct'].describe())",
        "    print()",
        "    if 'oos_avg_max_drawdown_pct' in top_10.columns:",
        "        print('=== Top-10 OOS Drawdown Distribution ===')",
        "        print(top_10['oos_avg_max_drawdown_pct'].describe())",
        "    if 'composite_score' in top_10.columns:",
        "        print()",
        "        print('=== Composite Score Distribution ===')",
        "        print(top_10['composite_score'].describe())",
        "else:",
        "    print('Top-10 data not available or missing OOS columns.')",
    ])


def _code_leaderboard_row(row: Optional[Dict[str, Any]]) -> str:
    """Cell that pretty-prints the leaderboard row for this run."""
    if row is None:
        return "# No leaderboard row available for this run."
    safe = json.dumps(row, ensure_ascii=False, default=str)
    return "\n".join([
        "# Leaderboard entry for this run",
        f"leaderboard_row = json.loads(r'''{safe}''')",
        "for k, v in leaderboard_row.items():",
        "    print(f'{k:40s}: {v}')",
    ])


def _md_notes_section() -> str:
    """Markdown cell with placeholder for user notes."""
    return "\n".join([
        "## Analysis Notes",
        "",
        "_Add your observations, hypotheses, or follow-up experiments here._",
        "",
        "---",
    ])


def _code_combo_summary_analysis() -> str:
    """Cell that analyses combo summary statistics."""
    return "\n".join([
        "# --- Combo Summary Statistics ---",
        "if not combo_summary.empty:",
        "    numeric_cols = combo_summary.select_dtypes(include='number').columns.tolist()",
        "    if numeric_cols:",
        "        print(f'Numeric columns ({len(numeric_cols)}):')",
        "        print(combo_summary[numeric_cols].describe().round(4))",
        "    print(f'\\nTotal combos evaluated: {len(combo_summary)}')",
        "    if 'regime_name' in combo_summary.columns:",
        "        print(f'\\nRegime distribution:')",
        "        print(combo_summary['regime_name'].value_counts())",
        "else:",
        "    print('Combo summary data not available.')",
    ])


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def build_experiment_notebook(
    run_id: str,
    out_dir: Path,
    *,
    metadata: Dict[str, Any],
    top10_df: Optional[Any] = None,
    combo_df: Optional[Any] = None,
    symbol_df: Optional[Any] = None,
    leaderboard_row: Optional[Dict[str, Any]] = None,
) -> Path:
    """Build and write an experiment notebook for *run_id*.

    Parameters
    ----------
    run_id : str
        The run identifier (e.g. ``"20260214_123456"``).
    out_dir : Path
        Directory where the ``.ipynb`` will be written (typically ``artifacts/``).
    metadata : dict
        Run metadata dict (from ``run_metadata.json``).
    top10_df : DataFrame or None
        Top-10 results; used only to determine the CSV filename pattern.
    combo_df : DataFrame or None
        Combo summary; used only to determine the CSV filename.
    symbol_df : DataFrame or None
        Symbol summary; used only to determine the CSV filename.
    leaderboard_row : dict or None
        Leaderboard row for this run.

    Returns
    -------
    Path
        Absolute path to the written ``.ipynb`` file.
    """
    nb = new_notebook()
    nb.metadata.kernelspec = {
        "display_name": "Python 3",
        "language": "python",
        "name": "python3",
    }
    nb.metadata.language_info = {
        "name": "python",
        "version": "3.11",
    }

    cells: List[nbformat.NotebookNode] = []

    # 1. Title + metadata table
    cells.append(new_markdown_cell(_md_metadata_section(metadata)))

    # 2. Imports
    cells.append(new_code_cell(_code_imports()))

    # 3. Load run metadata
    cells.append(new_code_cell(_code_load_metadata(run_id)))

    # 4. Load top-10
    top10_file = f"param_sweep_top10_{run_id}.csv"
    cells.append(new_code_cell(_code_load_csv("Top 10", top10_file, head=10)))

    # 5. Load combo summary
    combo_file = f"param_sweep_combo_summary_{run_id}.csv"
    cells.append(new_code_cell(_code_load_csv("Combo Summary", combo_file, head=20)))

    # 6. Load symbol summary
    symbol_file = f"param_sweep_symbol_summary_{run_id}.csv"
    cells.append(new_code_cell(_code_load_csv("Symbol Summary", symbol_file, head=20)))

    # 7. Leaderboard row
    cells.append(new_code_cell(_code_leaderboard_row(leaderboard_row)))

    # 8. Basic OOS analysis
    cells.append(new_code_cell(_code_basic_analysis()))

    # 9. Combo summary analysis
    cells.append(new_code_cell(_code_combo_summary_analysis()))

    # 10. Notes placeholder
    cells.append(new_markdown_cell(_md_notes_section()))

    nb.cells = cells

    out_path = Path(out_dir) / f"experiment_{run_id}.ipynb"
    out_path.parent.mkdir(parents=True, exist_ok=True)
    with open(out_path, "w", encoding="utf-8") as f:
        nbformat.write(nb, f)

    return out_path

