# -*- coding: utf-8 -*-
"""Constants extracted from run_btc_regime_sweep monolith (AWF-000 step 1).

AWF-112: Labels stored as plain UTF-8 strings (no more double-encoding).
"""

import html

from scripts.autowfo import strategy_schema as autowfo_strategy_schema


def _u(text):
    """Decode escaped Unicode literals for backward-compatible snapshots."""
    return text.encode("utf-8").decode("unicode_escape")


def _html_entity(text):
    """Resolve HTML entities for backward-compatible snapshots."""
    return html.unescape(text)


LABELS = {
    "report_title": "回測報告",
    "summary_title": "回測摘要",
    "params_title": "最佳參數",
    "top_title": "參數排行",
    "chart_title": "回測圖表",
    "symbol": "交易對",
    "filter_name": "指標組合",
    "vol_lookback": "波動回看(根)",
    "vol_z": "波動 Z 分數門檻",
    "mom_lookback": "動能回看(根)",
    "trade_mom_lookback": "交易幣動能回看(根)",
    "regime_name": "策略型態",
    "regime_type": "訊號類型",
    "vol_mode": "波動條件",
    "regime_rsi_long": "RSI 回歸多頭門檻",
    "regime_rsi_short": "RSI 回歸空頭門檻",
    "tp_stop": "獲利%出場",
    "sl_stop": "止損",
    "max_hold": "最長持有(根)",
    "rsi_window": "RSI 週期",
    "rsi_long": "RSI 多頭門檻",
    "rsi_short": "RSI 空頭門檻",
    "bb_width": "布林帶寬度門檻",
    "atr_ratio": "ATR/價格門檻",
    "total_return_pct": "總報酬(%)",
    "total_profit": "總盈利",
    "total_trades": "總交易筆數",
    "win_rate_pct": "勝率(%)",
    "avg_trade_pct": "平均每筆(%)",
    "max_drawdown_pct": "最大回撤(%)",
    "position_coverage_pct": "持倉覆蓋率(%)",
    "avg_total_return_pct": "平均總報酬(%)",
    "avg_win_rate_pct": "平均勝率(%)",
    "avg_avg_trade_pct": "平均每筆(%)",
    "avg_max_drawdown_pct": "平均最大回撤(%)",
    "avg_position_coverage_pct": "平均持倉覆蓋率(%)",
    "avg_total_trades": "平均總交易筆數",
    "min_total_trades": "最小總交易筆數",
    "avg_daily_trades": "平均每日交易次數",
    "avg_hold_hours": "平均持倉(小時)",
    "ma_fast": "MA 快線",
    "ma_slow": "MA 慢線",
    "macd_hist_ratio": "MACD 柱狀比率門檻",
    "stoch_long": "KD 多頭門檻",
    "stoch_short": "KD 空頭門檻",
    "obv_lookback": "OBV 回看(根)",
    "volume_lookback": "量能回看(根)",
    "volume_z": "量能 Z 分數門檻",
    "roc_lookback": "ROC 回看(根)",
    "roc_threshold": "ROC 門檻",
    "mfi_long": "MFI 多頭門檻",
    "mfi_short": "MFI 空頭門檻",
    "cmf_lookback": "CMF 回看(根)",
    "cmf_threshold": "CMF 門檻",
    "vroc_lookback": "量能變化率 回看(根)",
    "vroc_threshold": "量能變化率 門檻",
    "ad_lookback": "A/D 回看(根)",
    "cci_lookback": "CCI 回看(根)",
    "cci_long": "CCI 多頭門檻",
    "cci_short": "CCI 空頭門檻",
    "willr_lookback": "Williams %R 回看(根)",
    "willr_long": "Williams %R 多頭門檻",
    "willr_short": "Williams %R 空頭門檻",
    "adx_lookback": "ADX 回看(根)",
    "adx_threshold": "ADX 門檻",
    "trix_lookback": "TRIX 回看(根)",
    "dpo_lookback": "DPO 回看(根)",
    "efi_lookback": "Elder Force 回看(根)",
    "vwma_lookback": "VWMA 回看(根)",
    "ultosc_long": "Ultimate Osc 多頭門檻",
    "ultosc_short": "Ultimate Osc 空頭門檻",
    "keltner_lookback": "Keltner 回看(根)",
    "keltner_long": "Keltner 多頭門檻",
    "keltner_short": "Keltner 空頭門檻",
    "donchian_lookback": "Donchian 回看(根)",
    "donchian_long": "Donchian 多頭門檻",
    "donchian_short": "Donchian 空頭門檻",
    "ppo_threshold": "PPO 門檻",
    "chop_lookback": "波動指數 回看(根)",
    "chop_threshold": "波動指數 門檻",
    "oos_avg_total_return_pct": "驗證平均總報酬(%)",
    "oos_avg_win_rate_pct": "驗證平均勝率(%)",
    "oos_avg_avg_trade_pct": "驗證平均每筆(%)",
    "oos_avg_max_drawdown_pct": "驗證平均最大回撤(%)",
    "oos_avg_position_coverage_pct": "驗證平均持倉覆蓋率(%)",
    "oos_avg_total_trades": "驗證平均交易筆數",
    "oos_min_total_trades": "驗證最小交易筆數",
    "oos_avg_daily_trades": "驗證平均每日交易次數",
    "oos_avg_hold_hours": "驗證平均持倉(小時)",
    "oos_return_std": "驗證報酬標準差(%)",
    "oos_positive_segment_ratio": "驗證正報酬區段比率",
    "oos_sharpe_like": "OOS Sharpe-like",
    "oos_low_trade_segment_ratio": "驗證低交易區段比率",
    "oos_low_trade_penalty": "驗證低樣本懲罰",
    "oos_segments": "驗證區段數",
    "data_range": "資料區間",
    "scan_timeframes": "掃描時間框架",
    "timeframe": "時間框架",
    "data_days": "資料天數",
    "base_symbol": "基準幣對",
    "trade_symbols": "交易幣對",
    "capital_mode": "資金模式",
    "run_id": "執行編號",
    "timestamp_utc": "UTC 時間",
    "ranking_mode": "排名模式",
    "report": "報告",
    "min_trades_filter": "最小交易筆數門檻",
    "min_trades_target": "目標最小交易筆數",
    "min_avg_daily_trades_filter": "平均每日交易次數門檻",
    "min_avg_daily_trades_target": "目標平均每日交易次數",
    "history_title": "歷史累積",
    "leaderboard_title": "歷史排行榜",
    "recent_runs_title": "最近執行紀錄",
    "plot_symbol": "圖表幣對",
    "oos_summary_title": "驗證摘要",
    "wf_train_days": "訓練期間(天)",
    "wf_test_days": "驗證期間(天)",
    "wf_step_days": "前進步長(天)",
    "wf_valid_days": "WF Valid Days",
    "wf_mode": "切分模式",
    "wf_segments": "驗證區段數",
    "status_title": "執行狀態",
    "status_stage": "階段",
    "status_total": "總組合",
    "status_done": "已完成",
    "status_remaining": "剩餘",
    "status_skipped": "已跳過",
    "status_percent": "進度(%)",
    "status_elapsed": "經過時間",
    "status_eta": "預計剩餘",
    "status_updated": "更新時間",
    "init_cash_usdt": "起始資金(USDT)",
    "order_size_pct": "單筆住倉(比例)",
    "max_concurrent_positions": "最大同時持倉",
    "indicator_list": "指標清單",
    "indicator_count": "指標數量",
    "slippage_bps": "滑點(bps)",
    "spread_bps": "價差(bps)",
    "funding_rate_daily": "資金費率/日",
    "sym_avg_total_return_pct": "幣對平均總報酬(%)",
    "sym_avg_win_rate_pct": "幣對平均勝率(%)",
    "sym_avg_avg_trade_pct": "幣對平均每筆(%)",
    "sym_avg_max_drawdown_pct": "幣對平均最大回撤(%)",
    "sym_avg_position_coverage_pct": "幣對平均持倉覆蓋率(%)",
    "sym_avg_total_trades": "幣對平均交易筆數",
    "sym_min_total_trades": "幣對最小交易筆數",
    "sym_avg_daily_trades": "幣對平均每日交易次數",
    "sym_avg_hold_hours": "幣對平均持倉(小時)",
}

# Backward-compatible label snapshots used by characterization tests.
LABELS["report_title"] = _html_entity(_u("\\u56de\\u6e2c\\u5831\\u544a"))
LABELS["status_title"] = _html_entity(_u("\\u57f7\\u884c\\u72c0\\u614b"))

FILTER_NAME_MAP = {
    "vol_mom": "波動+動能",
    "vol_mom_rsi": "波動+動能+RSI",
    "vol_mom_bb": "波動+動能+布林帶寬度",
    "vol_mom_atr": "波動+動能+ATR/價格",
    "vol_mom_rsi_bb": "波動+動能+RSI+布林帶寬度",
    "vol_mom_rsi_atr": "波動+動能+RSI+ATR/價格",
    "vol_mom_ma": "波動+動能+MA",
    "vol_mom_macd": "波動+動能+MACD",
    "vol_mom_stoch": "波動+動能+KD",
    "vol_mom_obv": "波動+動能+OBV",
    "vol_mom_volume": "波動+動能+量能",
    "none": "無額外濾網",
}

STRATEGY_SCHEMA = autowfo_strategy_schema.load_strategy_schema()
INDICATOR_META = autowfo_strategy_schema.build_indicator_meta(
    STRATEGY_SCHEMA,
    label_transform=None,
)
INDICATOR_LABELS = {key: value["label"] for key, value in INDICATOR_META.items()}

INDICATOR_PARAM_FIELDS = [
    "rsi_long",
    "rsi_short",
    "bb_width",
    "atr_ratio",
    "ma_fast",
    "ma_slow",
    "macd_hist_ratio",
    "stoch_long",
    "stoch_short",
    "obv_lookback",
    "volume_lookback",
    "volume_z",
    "roc_lookback",
    "roc_threshold",
    "mfi_long",
    "mfi_short",
    "cmf_lookback",
    "cmf_threshold",
    "vroc_lookback",
    "vroc_threshold",
    "ad_lookback",
    "cci_lookback",
    "cci_long",
    "cci_short",
    "willr_lookback",
    "willr_long",
    "willr_short",
    "adx_lookback",
    "adx_threshold",
    "trix_lookback",
    "dpo_lookback",
    "efi_lookback",
    "vwma_lookback",
    "ultosc_long",
    "ultosc_short",
    "keltner_lookback",
    "keltner_long",
    "keltner_short",
    "donchian_lookback",
    "donchian_long",
    "donchian_short",
    "ppo_threshold",
    "chop_lookback",
    "chop_threshold",
]


REGIME_NAME_MAP = autowfo_strategy_schema.build_regime_name_map(
    STRATEGY_SCHEMA,
    label_transform=None,
)
REGIME_TYPE_MAP = autowfo_strategy_schema.build_regime_type_map(
    STRATEGY_SCHEMA,
    label_transform=None,
)
